@startuml Command_Execution_Activation
participant MoneyTrail as ":MoneyTrail"
participant Parser as ":Parser"
participant ":AddExpenseCommand" as AEC
participant MoneyList as ":MoneyList"

activate MoneyTrail
MoneyTrail -> Parser : "parseCommand(input)"
activate Parser
Parser -> AEC : new()
Parser --> MoneyTrail : AEC instance
deactivate Parser

MoneyTrail -> AEC : execute()
activate AEC
AEC -> MoneyList : "addExpense()"
activate MoneyList
MoneyList --> AEC
deactivate MoneyList
AEC --> MoneyTrail
deactivate AEC
deactivate MoneyTrail
@enduml