@startuml Exit_Sequence
actor User
participant Parser
participant ExitCommand
participant MoneyTrail
participant Storage
participant TextUI

User -> Parser : "exit"
activate Parser
Parser -> ExitCommand : parseCommand()
activate ExitCommand
ExitCommand --> Parser
deactivate ExitCommand
Parser --> MoneyTrail : ExitCommand
deactivate Parser

MoneyTrail -> ExitCommand : execute()
activate ExitCommand
ExitCommand -> MoneyTrail : setShouldExit(true)
activate MoneyTrail
MoneyTrail --> ExitCommand
deactivate MoneyTrail

ExitCommand -> Storage : saveEntries()
activate Storage
Storage --> ExitCommand
deactivate Storage

ExitCommand -> TextUI : printExitMsg()
activate TextUI
TextUI --> User : "Thank you..."
TextUI --> ExitCommand
deactivate TextUI
ExitCommand --> MoneyTrail
deactivate ExitCommand
@enduml
