@startuml
actor User
participant Parser as ":Parser"
participant CommandExecutor as ":CommandExecutor"
participant TextUI as ":TextUI"

User -> Parser : "help"
activate Parser

Parser -> CommandExecutor : parse("help")
activate CommandExecutor

CommandExecutor -> TextUI : getCommandList()
activate TextUI

TextUI --> CommandExecutor : commandList
deactivate TextUI

CommandExecutor --> Parser : parsedCommand
deactivate CommandExecutor

Parser --> User :
deactivate Parser

User -> TextUI :
activate TextUI
TextUI -> User : Display Command List
deactivate TextUI
@enduml
