@startuml Income_Seq
participant MoneyList as ":MoneyList"
create Income as ":Income"

activate MoneyList
MoneyList -> Income : **new**("Salary", 3000, "2023-10-01")
activate Income

Income -> Income : setDefaultsIfNull()
activate Income
Income --> Income:
deactivate Income

Income --> MoneyList : Income instance
deactivate Income
destroy Income
deactivate MoneyList
@enduml